spring.application.name=crud-spring

spring.datasource.url=jdbc:h2:mem:MY_DB_PROD
spring.datasource.username=sa
spring.datasource.password=gig@loc20

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.orm.jdbc.bind=trace

# H2 Console (Para você testar no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#http://localhost:8080/h2-console#

spring.web.error.include-stacktrace=never
spring.web.error.include-message=never

springdoc.swagger-ui.operationsSorter=alpha