package com.guilhermeneto.crud_spring.repository;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import com.guilhermeneto.crud_spring.models.Parceiros;

public class ParceirosDataSource {

    public static List<Parceiros> getParceiros() {
        return Arrays.asList(
            new Parceiros(null, 1, "Hydrogen", new BigDecimal("1.0079"), "H"),
			new Parceiros(null, 2, "Helium", new BigDecimal("4.0026"), "He"),
			new Parceiros(null, 3, "Lithium", new BigDecimal("6.941"), "Li"),
			new Parceiros(null, 4, "Beryllium", new BigDecimal("9.0122"), "Be"),
			new Parceiros(null, 5, "Boron", new BigDecimal("10.811"), "B"),
			new Parceiros(null, 6, "Carbon", new BigDecimal("12.0107"), "C"),
			new Parceiros(null, 7, "Nitrogen", new BigDecimal("14.0067"), "N"),
			new Parceiros(null, 8, "Oxygen", new BigDecimal("15.9994"), "O"),
			new Parceiros(null, 9, "Fluorine", new BigDecimal("18.9984"), "F"),
			new Parceiros(null, 10, "Neon", new BigDecimal("20.1797"), "Ne"),
			new Parceiros(null, 11, "Sodium", new BigDecimal("22.9898"), "Na"),
			new Parceiros(null, 12, "Magnesium", new BigDecimal("24.305"), "Mg"),
			new Parceiros(null, 13, "Aluminum", new BigDecimal("26.9815"), "Al"),
			new Parceiros(null, 14, "Silicon", new BigDecimal("28.0855"), "Si"),
			new Parceiros(null, 15, "Phosphorus", new BigDecimal("30.9738"), "P"),
			new Parceiros(null, 16, "Sulfur", new BigDecimal("32.065"), "S"),
			new Parceiros(null, 17, "Chlorine", new BigDecimal("35.453"), "Cl"),
			new Parceiros(null, 18, "Argon", new BigDecimal("39.948"), "Ar"),
			new Parceiros(null, 19, "Potassium", new BigDecimal("39.0983"), "K"),
			new Parceiros(null, 20, "Calcium", new BigDecimal("40.078"), "Ca"),
			new Parceiros(null, 21, "Scandium", new BigDecimal("44.9559"), "Sc"),
			new Parceiros(null, 22, "Titanium", new BigDecimal("47.867"), "Ti"),
			new Parceiros(null, 23, "Vanadium", new BigDecimal("50.9415"), "V"),
			new Parceiros(null, 24, "Chromium", new BigDecimal("51.9961"), "Cr"),
			new Parceiros(null, 25, "Manganese", new BigDecimal("54.938"), "Mn"),
			new Parceiros(null, 26, "Iron", new BigDecimal("55.845"), "Fe"),
			new Parceiros(null, 27, "Cobalt", new BigDecimal("58.9332"), "Co"),
			new Parceiros(null, 28, "Nickel", new BigDecimal("58.6934"), "Ni"),
			new Parceiros(null, 29, "Copper", new BigDecimal("63.546"), "Cu"),
			new Parceiros(null, 30, "Zinc", new BigDecimal("65.38"), "Zn"),
			new Parceiros(null, 31, "Gallium", new BigDecimal("69.723"), "Ga"),
			new Parceiros(null, 32, "Germanium", new BigDecimal("72.63"), "Ge"),
			new Parceiros(null, 33, "Arsenic", new BigDecimal("74.9216"), "As"),
			new Parceiros(null, 34, "Selenium", new BigDecimal("78.96"), "Se"),
			new Parceiros(null, 35, "Bromine", new BigDecimal("79.904"), "Br"),
			new Parceiros(null, 36, "Krypton", new BigDecimal("83.798"), "Kr"),
			new Parceiros(null, 37, "Rubidium", new BigDecimal("85.4678"), "Rb"),
			new Parceiros(null, 38, "Strontium", new BigDecimal("87.62"), "Sr"),
			new Parceiros(null, 39, "Yttrium", new BigDecimal("88.9059"), "Y"),
			new Parceiros(null, 40, "Zirconium", new BigDecimal("91.224"), "Zr"),
			new Parceiros(null, 41, "Niobium", new BigDecimal("92.9064"), "Nb"),
			new Parceiros(null, 42, "Molybdenum", new BigDecimal("95.94"), "Mo"),
			new Parceiros(null, 43, "Technetium", new BigDecimal("98"), "Tc"),
			new Parceiros(null, 44, "Ruthenium", new BigDecimal("101.07"), "Ru"),
			new Parceiros(null, 45, "Rhodium", new BigDecimal("102.9055"), "Rh"),
			new Parceiros(null, 46, "Palladium", new BigDecimal("106.42"), "Pd"),
			new Parceiros(null, 47, "Silver", new BigDecimal("107.8682"), "Ag"),
			new Parceiros(null, 48, "Cadmium", new BigDecimal("112.411"), "Cd"),
			new Parceiros(null, 49, "Indium", new BigDecimal("114.818"), "In"),
			new Parceiros(null, 50, "Tin", new BigDecimal("118.71"), "Sn"),
			new Parceiros(null, 51, "Antimony", new BigDecimal("121.76"), "Sb"),
			new Parceiros(null, 52, "Tellurium", new BigDecimal("127.6"), "Te"),
			new Parceiros(null, 53, "Iodine", new BigDecimal("126.9045"), "I"),
			new Parceiros(null, 54, "Xenon", new BigDecimal("131.293"), "Xe"),
			new Parceiros(null, 55, "Cesium", new BigDecimal("132.9055"), "Cs"),
			new Parceiros(null, 56, "Barium", new BigDecimal("137.327"), "Ba"),
			new Parceiros(null, 57, "Lanthanum", new BigDecimal("138.9055"), "La"),
			new Parceiros(null, 58, "Cerium", new BigDecimal("140.116"), "Ce"),
			new Parceiros(null, 59, "Praseodymium", new BigDecimal("140.9077"), "Pr"),
			new Parceiros(null, 60, "Neodymium", new BigDecimal("144.242"), "Nd"),
			new Parceiros(null, 61, "Promethium", new BigDecimal("145"), "Pm"),
			new Parceiros(null, 62, "Samarium", new BigDecimal("150.36"), "Sm"),
			new Parceiros(null, 63, "Europium", new BigDecimal("151.964"), "Eu"),
			new Parceiros(null, 64, "Gadolinium", new BigDecimal("157.25"), "Gd"),
			new Parceiros(null, 65, "Terbium", new BigDecimal("158.9254"), "Tb"),
			new Parceiros(null, 66, "Dysprosium", new BigDecimal("162.5"), "Dy"),
			new Parceiros(null, 67, "Holmium", new BigDecimal("164.9303"), "Ho"),
			new Parceiros(null, 68, "Erbium", new BigDecimal("167.259"), "Er"),
			new Parceiros(null, 69, "Thulium", new BigDecimal("168.9342"), "Tm"),
			new Parceiros(null, 70, "Ytterbium", new BigDecimal("173.04"), "Yb"),
			new Parceiros(null, 71, "Lutetium", new BigDecimal("174.967"), "Lu"),
			new Parceiros(null, 72, "Hafnium", new BigDecimal("178.49"), "Hf"),
			new Parceiros(null, 73, "Tantalum", new BigDecimal("180.9479"), "Ta"),
			new Parceiros(null, 74, "Tungsten", new BigDecimal("183.84"), "W"),
			new Parceiros(null, 75, "Rhenium", new BigDecimal("186.207"), "Re"),
			new Parceiros(null, 76, "Osmium", new BigDecimal("190.23"), "Os"),
			new Parceiros(null, 77, "Iridium", new BigDecimal("192.217"), "Ir"),
			new Parceiros(null, 78, "Platinum", new BigDecimal("195.084"), "Pt"),
			new Parceiros(null, 79, "Gold", new BigDecimal("196.9666"), "Au"),
			new Parceiros(null, 80, "Mercury", new BigDecimal("200.59"), "Hg"),
			new Parceiros(null, 81, "Thallium", new BigDecimal("204.3833"), "Tl"),
			new Parceiros(null, 82, "Lead", new BigDecimal("207.2"), "Pb"),
			new Parceiros(null, 83, "Bismuth", new BigDecimal("208.9804"), "Bi"),
			new Parceiros(null, 84, "Polonium", new BigDecimal("209"), "Po"),
			new Parceiros(null, 85, "Astatine", new BigDecimal("210"), "At"),
			new Parceiros(null, 86, "Radon", new BigDecimal("222"), "Rn"),
			new Parceiros(null, 87, "Francium", new BigDecimal("223"), "Fr"),
			new Parceiros(null, 88, "Radium", new BigDecimal("226"), "Ra"),
			new Parceiros(null, 89, "Actinium", new BigDecimal("227"), "Ac"),
			new Parceiros(null, 90, "Thorium", new BigDecimal("232.0381"), "Th"),
			new Parceiros(null, 91, "Protactinium", new BigDecimal("231.0359"), "Pa"),
			new Parceiros(null, 92, "Uranium", new BigDecimal("238.0289"), "U"),
			new Parceiros(null, 93, "Neptunium", new BigDecimal("237"), "Np"),
			new Parceiros(null, 94, "Plutonium", new BigDecimal("244"), "Pu"),
			new Parceiros(null, 95, "Americium", new BigDecimal("243"), "Am"),
			new Parceiros(null, 96, "Curium", new BigDecimal("247"), "Cm"),
			new Parceiros(null, 97, "Berkelium", new BigDecimal("247"), "Bk"),
			new Parceiros(null, 98, "Californium", new BigDecimal("251"), "Cf"),
			new Parceiros(null, 99, "Einsteinium", new BigDecimal("252"), "Es"),
			new Parceiros(null, 100, "Fermium", new BigDecimal("257"), "Fm"),
			new Parceiros(null, 101, "Mendelevium", new BigDecimal("258"), "Md"),
			new Parceiros(null, 102, "Nobelium", new BigDecimal("259"), "No"),
			new Parceiros(null, 103, "Lawrencium", new BigDecimal("262"), "Lr"),
			new Parceiros(null, 104, "Rutherfordium", new BigDecimal("267"), "Rf"),
			new Parceiros(null, 105, "Dubnium", new BigDecimal("270"), "Db"),
			new Parceiros(null, 106, "Seaborgium", new BigDecimal("271"), "Sg"),
			new Parceiros(null, 107, "Bohrium", new BigDecimal("270"), "Bh"),
			new Parceiros(null, 108, "Hassium", new BigDecimal("277"), "Hs"),
			new Parceiros(null, 109, "Meitnerium", new BigDecimal("278"), "Mt"),
			new Parceiros(null, 110, "Darmstadtium", new BigDecimal("281"), "Ds"),
			new Parceiros(null, 111, "Roentgenium", new BigDecimal("282"), "Rg"),
			new Parceiros(null, 112, "Copernicium", new BigDecimal("285"), "Cn"),
			new Parceiros(null, 113, "Nihonium", new BigDecimal("286"), "Nh"),
			new Parceiros(null, 114, "Flerovium", new BigDecimal("289"), "Fl"),
			new Parceiros(null, 115, "Moscovium", new BigDecimal("290"), "Mc"),
			new Parceiros(null, 116, "Livermorium", new BigDecimal("293"), "Lv"),
			new Parceiros(null, 117, "Tennessine", new BigDecimal("294"), "Ts"),
			new Parceiros(null, 118, "Oganesson", new BigDecimal("294"), "Og"),

			new Parceiros(null, 119,"Teste119", new BigDecimal("87.45"),"Ts")
        );
    }
}
